version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      FIREBASE_CREDENTIAL_PATH: /etc/hostego/firebase.json
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - /etc/hostego/firebase.json:/etc/hostego/firebase.json
    entrypoint: [ "/wait-for.sh", "db:5432", "--", "./backend-hostego" ]

volumes:
  pgdata:
