version: '3.8'

services:

  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      FIREBASE_CREDENTIAL_PATH: /etc/hostego/firebase.json
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - /etc/hostego/firebase.json:/etc/hostego/firebase.json
    entrypoint: [ "/wait-for.sh", "172.17.0.1:5432", "./backend-hostego" ]
