version: "3.9"

services:
  backend:
    build: .
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      HOSTEGO_JWT_SECRET_DEV: ${HOSTEGO_JWT_SECRET_DEV}
    volumes:
      - /etc/hostego/firebase.json:/etc/hostego/firebase.json
      - ./.env:/app/.env
    restart: unless-stopped
