name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: ✅ Setup SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_deploy
          chmod 600 ~/.ssh/github_deploy
          ssh-keyscan -H 147.93.103.151 >> ~/.ssh/known_hosts

      - name: 🚀 Deploy to VPS
        run: |
          ssh -i ~/.ssh/github_deploy -o StrictHostKeyChecking=no root@147.93.103.151 << 'EOF'
          cd /root
          ./deploy.sh
          EOF
